// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lququtvgfdvplhkselfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxdXF1dHZnZmR2cGxoa3NlbGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMjEzMTEsImV4cCI6MjA1NzU5NzMxMX0.kruLD0RXU1xj2uMeRXrcKF7HMGwpQRM3FpIDYK40180";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);